### ISSUE TITLE
Self-hosted on Railways - issue with reCAPTCHA

### ISSUE THREAD

**Issue by KazeroG** [ever-co/ever-teams#1983]
There is a deploying issue with reCAPTCHA on Railway. Are there any .env configurations required?

![image](https://github.com/ever-co/ever-teams/assets/17680194/7d20678b-2145-4463-b288-8297e9260efe)

Template used : https://railway.app/template/7_OfzR?referralCode=40jeja

**Comment by evereq** [comment]
@paradoxe35 I remember we should have a code that disable ReCaptcha if keys (public / secret) are not set in env vars, can you check?

**Comment by paradoxe35** [comment]
@evereq 
Let me check

**Comment by evereq** [comment]
@KazeroG we did some fixes for that (already merged), can you try again please?

**Comment by barnabynagy** [comment]
I have the same issue, how to fix this error?

**Comment by evereq** [comment]
@GloireMutaliko21 can you check that if reCaptcha env vars are not set, app works well without reCaptcha protection? Maybe somehow it stop working well in such case and so deploy to Railways using template fails as no reCaptcha keys are set?

@barnabynagy can you try to SET env vars inside Railway so that it enable reCaptcha (recommended), see https://github.com/ever-co/ever-teams/blob/develop/apps/web/.env#L12 env vars names to set and register with Google Recaptcha service https://cloud.google.com/security/products/recaptcha

**Comment by GloireMutaliko21** [comment]
@barnabynagy I deployed on Railway with empty env vars for `CAPTCHA_SECRET_KEY` and `NEXT_PUBLIC_CAPTCHA_SITE_KEY` and registered with team creation and every thing works successfully. This problem is probably linked to the wrong keys being passed to these two variables.

My deployment is here : [](https://web-production-f9c7.up.railway.app/auth/passcode)

**Comment by barnabynagy** [comment]
> NEXT_PUBLIC_CAPTCHA_SITE_KEY



> @barnabynagy I deployed on Railway with empty env vars for `CAPTCHA_SECRET_KEY` and `NEXT_PUBLIC_CAPTCHA_SITE_KEY` and registered with team creation and every thing works successfully. This problem is probably linked to the wrong keys being passed to these two variables.
> 
> My deployment is here : https://web-production-f9c7.up.railway.app/auth/passcode

Ah ok, If I add those variables then it works fine. The template should be edited that those variables are there by default and empty.

**Comment by barnabynagy** [comment]
> @barnabynagy I deployed on Railway with empty env vars for `CAPTCHA_SECRET_KEY` and `NEXT_PUBLIC_CAPTCHA_SITE_KEY` and registered with team creation and every thing works successfully. This problem is probably linked to the wrong keys being passed to these two variables.
> 
> My deployment is here : https://web-production-f9c7.up.railway.app/auth/passcode

Still have the captcha issue even though I added the variables.

**Comment by evereq** [comment]
@barnabynagy what we describe is that if you added variables, the values of them must be correct values, otherwise ReCaptch will fail to render. Double check what values you are using OR just remove values completely to disable reCaptcha fully.

**Comment by barnabynagy** [comment]
I added those two variables with empty values as suggested and produces the same error.

**Comment by evereq** [comment]
@barnabynagy error displayed in your screenshot tells something about domain name etc. It means that values are submitted somehow, not sure how is that possible if you set values to be empty!? Please record full video of what you are doing, we will try to help more, but at this stage we don't understand what cause issues for you. Basically we have in our code basic check - if env vars are empty / not defined, it should DISABLE ReCaptcha completely and this is what our engineer @GloireMutaliko21 tested using his personal Railway account...... (reproducing everything from 0)

**Comment by barnabynagy** [comment]
See the image
![CleanShot 2024-06-09 at 07 57 13](https://github.com/ever-co/ever-teams/assets/650475/b2f152a1-d7b3-44c3-a8a5-4bf15046d055)
