### ISSUE TITLE
[Improvement] Login | The system should remember the latest Workspace and Team

### ISSUE THREAD

**Issue by KostyaEver** [ever-co/ever-teams#2710]
The issue is that now it selects just the first team (maybe also the workspace). 

Should select the latest where the user was

On the screen how it selects now:
<img width="1507" alt="Screenshot at Jul 11 10-42-59" src="https://github.com/ever-co/ever-teams/assets/107203576/cdda80fd-b430-4fbd-b4c0-e68d0fbc3a2e">

But in reality RED was the latest team

On the screen how it should be
<img width="731" alt="Screenshot at Jul 11 10-43-21" src="https://github.com/ever-co/ever-teams/assets/107203576/22d7cd9a-57cd-488d-b678-b8b7b51f2b35">

**Comment by GloireMutaliko21** [comment]
@KostyaEver please this recently closed ticket https://github.com/ever-co/ever-teams/issues/2678
Can you please test if it's not fixed yet ???
CC: @evereq

**Comment by CREDO23** [comment]
This is fixed if you use email + password! 
I don't know if it works with pagic link / code

**Comment by CREDO23** [comment]
@KostyaEver, we should close this ... It works!

**Comment by KostyaEver** [comment]
it works now, unfortunately #2678 did not resolve issue it was not fully completed that's why I created this one
